export * from './Register'
export * from './CheckCode'
export * from './Login'
export * from './Dashboard'
export * from './ForgotPassword'
export * from "./UpdateUser"
export * from "./ChangePassword"
export * from "./CrearActivity"
export * from "./ActivitiesFeed"
export * from "./ActivityDetailPage"
export * from "./Profile"
export * from "./CreateMessage"
export * from "./Home"
export * from "./Contact"
export * from "./UpdateActivity"
export * from "./Calendar"
export * from "./BookingDay"
export * from "./ActivityListSuperAdmin"
export * from "./SuperAdminPanel"
export * from "./BookingsFeed"
export * from "./CreateNewDay"
export * from "./ContactMessage"